### ISSUE TITLE
Where is the Orthogonal Jump Point finder?

### ISSUE THREAD

**Issue by VincentMeier** [qiao/PathFinding.js#107]
I noticed that in the visual demo of this plugin, the Orthogonal Jump Point search produces exactly the result I wish to use in my game, but after installing the latest build of this library in my project I can find and use the following finders:
AStarFinder
BestFirstFinder
BreadthFirstFinder
DijkstraFinder
IDAStarFinder.js
JumpPointFinder
BiAStarFinder
BiBestFirstFinder
BiBreadthFirstFinder
BiDijkstraFinder
but NOT the OrthogonalJumpPointFinder.

And if I try and use the JumpPointFinder and then just disabling diagonal search, it still searches diagonally. My guess is that this finder got removed with updates due to some reason and I just have to use the other finders, but maybe I'm wrong and someone here can explain how I can get the functionality of the Orthogonal Jump Point search, like it's shown in the visual demo.

**Comment by qiao** [comment]
Hi Vincent, Have you tried passing in `diagonalMovement: PF.DiagonalMovement.Never` while constructing the JumpPointFinder? 
Example: https://github.com/qiao/PathFinding.js/blob/master/visual/js/panel.js#L149

**Comment by VincentMeier** [comment]
Oh hadn't found that option before. Yes this does exactly what I wanted it to do. Much obliged.
