### ISSUE TITLE
Problem with the findPath function

### ISSUE THREAD

**Issue by ssannkkallpp** [qiao/PathFinding.js#118]
I have version 4.0.17 and the findPath function does not work. When I do
var path = finder.findPath(i,j,k,l,grid);
console.log(path[0]);

I get an error saying, "cannot read property 0 of undefined".

Any idea why?

**Comment by imor** [comment]
Please post your full code and data. Looks like the findPath is returning and undefined value.

**Comment by ssannkkallpp** [comment]
I fixed the problem myself.
