### ISSUE TITLE
pathfinding-browser.min.js:1 Uncaught TypeError: Cannot read property '1' of undefinedr.getNodeAt @ pathfinding-browser.min.js:1r.findPath @ pathfinding-browser.min.js:1(anonymous function)

### ISSUE THREAD

**Issue by cwwjie** [qiao/PathFinding.js#119]
var matrix = [
    [0, 0, 0, 1, 0],
    [1, 0, 0, 0, 1],
    [0, 0, 1, 0, 0],
];
var grid = new PF.Grid(matrix);
↓
var matrix = [
    [0, 0, 0, 1, 0],
    [1, 0, 0, 0, 1],
    [0, 0, 1, 0, 0],
];
var grid = new PF.Grid(5, 3, matrix);

**Comment by PlayMa256** [comment]
well, i'm having this issue too. I could'nt find in the documentation a way to manually create your grid to be able to see it on the visualization tool. Is there any way?

**Comment by cwwjie** [comment]
(｡･ω･｡)ﾉ♡ I was using "console.log (grid)" to detect  grid 。
This PathFinding.js demo is→http://qiao.github.io/PathFinding.js/visual/ ，And this demo match file is in https://github.com/qiao/PathFinding.js/tree/master/visual。
But this demo is too hard for me to understand，You can see my demo (write in recent and not good But it may simply)
→http://www.cwwtswua.com/Baidu_IFE_Task/Baidu_IFE_Task_46_By_Kallen_Sunshine/Baidu_IFE_Task_46_By_Kallen_Sunshine.html，https://github.com/cwwjie/Baidu_Ife_task/tree/master/The_third_stage_of_the_task/Baidu_IFE_Task_46_By_Kallen_Sunshine。

**Comment by PlayMa256** [comment]
Well, thats where i looked at. I tried to replace the grid where its instantiated `new PF(grid)` but i had the same issue as you. I'm gonna try your demo later today. Lets wait the oficial answer. Thanks for contribution.

**Comment by imor** [comment]
I'm not sure what you are trying to do. Are you running the visualization offline?Are you running it in the browser or in node.js? Can you post the exact code that is causing the problem and the exact location where the exception is thrown.

**Comment by cwwjie** [comment]
Oh,it just ok. PathFinding.js is proper. It is  operational miss.I was trying to HTML5 game.and it running  in the Google Chrome browser .my problem is when i use "matrix=[]" . and "var grid = new PF.Grid(matrix);" then console throw error (like title ↑) So I found use "var grid = new PF.Grid(5,6,RDwall);" is  proper. and i wish to modify "readne.md" explanation.

**Comment by imor** [comment]
Ok, in that case can I close this issue?

**Comment by cwwjie** [comment]
yes,is ok.(｡･ω･｡)ﾉ♡
