### ISSUE TITLE
API for web release is vastly different from npm release

### ISSUE THREAD

**Issue by sadtaco** [qiao/PathFinding.js#120]
https://github.com/imor/pathfinding-bower/releases the source for "function Grid" is very different than how it is for the npm release, for example. There is no width_or_matrix for the first arg.

It's very confusing.

**Comment by imor** [comment]
Thanks for pointing out. Last few releases were made on npm only and were missing for bower. This is fixed with a new release: 0.4.18

**Comment by sadtaco** [comment]
Thanks for the quick update.
