### ISSUE TITLE
Directional condition

### ISSUE THREAD

**Issue by pellejacobs** [qiao/PathFinding.js#134]
How would one go about implementing a directional condition on a path? 

Take for example a ledge you can jump off: jumping of the ledge would be a valid path but the other way around would be invalid.

**Comment by rohan-deshpande** [comment]
I'm not super clear on what you mean exactly but it seems like you are talking about cost. Cost has been implemented via a fork which you can find here https://github.com/paulrobello/PathFinding.js

**Comment by pellejacobs** [comment]
Not costs. I mean a tile you can only get to from one direction. Take eg. the ledges from [vim-adventures](http://vim-adventures.com/). You can get onto the tile from left to right, but not from right to left.

![vim_adventures](https://cloud.githubusercontent.com/assets/7174652/18354345/7b0f9e5c-75e5-11e6-8df2-310f7c476a10.jpg)

**Comment by rohan-deshpande** [comment]
What you are doing sort of goes outside the scope of Pathfinding js, as it's predominantly for 2D grid based path finding. What you have here IS a grid, albeit not exactly 2D. 

I'm achieving something similar to what you are doing in my game (which is 3D); I achieve this via a unit jump score and height properties for each tile. But this is a little different - is it your intention that the ramp is ONLY accessible from the front? Can the character access it if they are on either one of the stone walls adjacent to it (jump down onto it basically?)

**Comment by pellejacobs** [comment]
Good question. In my case not, as the walls are not accessible anyway. 

However, I noticed I need even a more custom condition, as I have bridges as well. I'll just fork and try to figure it out. Thanks for your help! 😄

**Comment by mohamedmansour** [comment]
@pellejacobs easystar has directional conditions and cost as well https://github.com/prettymuchbryce/easystarjs
