### ISSUE TITLE
[Help] How to use this library with a d3.js network graph?

### ISSUE THREAD

**Issue by Risingson** [qiao/PathFinding.js#139]
How can i use this library with d3.js edges ? Do i have to convert them to a simple matrix (how would i do that) ? Or can it be used with d3.js data straight away somehow ? 

d3.js edges data structure for example: 
`[{"source":0,"target":1},{"source":0,"target":2},{"source":2,"target":3}, ...]`

Or asked another way: Is there a way to use this library with a graph instead of a grid ?

**Comment by mfandl** [comment]
Sounds like overkill to me. If you just want to search for a path in your graph, I think it is easier to write a graph path search algorithm like [Dijskstra's](https://en.wikipedia.org/wiki/Dijkstra's_algorithm) from scratch.

If you still want to use this library, you first need to provide a bit more details about your data representation and goal. You definitely could create a matrix where each cell represents a node and neighboring cells have edge between them, but your options are very limited if you want to avoid extending this library. How would you distinguish between one directional and bidirectional edge for example? Or how would you make a node connected with 9 nodes on a grid, where there are only 8 cells arund each other cell?

It might be that I do not understand what you are trying to achieve, but I would suggest you to either look for a more suitable library, or write your own solution. Both of these options will imo be easier.

**Comment by Risingson** [comment]
I wanted to try different algorithms like A*, Djikstra, BFS to benchmark without writing them on my own (am not a pro).

I asked this question and edited over at stackoverflow aswell: http://stackoverflow.com/questions/41753503/finding-a-shortest-path-within-a-d3-js-network-graph-using-an-algorithm-library

However I guess i cannot use this library for it sadly :(

**Comment by mfandl** [comment]
@Risingson i see. i guess you really shoudld search for another solution. try searching for graph search library in javascript. i am sure you will find something useful. also i would suggest using d3 just as a visualisation layer and do the search in another layer. be it your own code or a specific library. good luck!

**Comment by Risingson** [comment]
I ended up using Cytoscape.js (A*) and JSNetworkX (BFS) for finding a shortest path in a network graph.
