### ISSUE TITLE
find the farthest tile away

### ISSUE THREAD

**Issue by SirJosh3917** [qiao/PathFinding.js#154]
how do i do that

**Comment by brean** [comment]
Simply calculate the distance for every tile from a start point (e.g. `var distance = math.abs(node.x - start.x) + math.abs(node.y - start.y)` ) and take the one with the biggest distance value. Note that this will not garantee you that there is a path from the start to that node, so you also need to check that, but if you just want the farthest tile that should be the simpelest solution (that can also be optimized based on your data e.g. check the borders of your grid first and then go inward if you didn't found any walkable nodes).
