### ISSUE TITLE
dontCrossCorners no effect

### ISSUE THREAD

**Issue by weishuluo** [qiao/PathFinding.js#158]
I have already set allowDiagonal: true,  but dontCrossCorners not effect ,it still can't cross corners

**Comment by brean** [comment]
I don't think I understand what you mean, the don't cross corners feature works as I would expect it.
Without don't cross corners the algorithm can go though the corners of a wall:
![the path goes thorugh the cordners](http://andreasbresser.de/cross_corners.PNG)
with don't cross corners it makes some space:
![the path takes some extra space from the cordners](http://andreasbresser.de/dont_cross_corners.PNG)

**Comment by weishuluo** [comment]
way 1
![qq 20180411105820](https://user-images.githubusercontent.com/7087635/38594079-485c7af6-3d77-11e8-8aeb-480d7a349b34.png)

way 2
![qq 20180411105909](https://user-images.githubusercontent.com/7087635/38594108-64976f8c-3d77-11e8-9948-c66e16bdd94d.png)

I thought it can find a way in way 2.
So I misunderstand it's meaning ...
