### ISSUE TITLE
finder.findpath

### ISSUE THREAD

**Issue by lenskyAI123** [qiao/PathFinding.js#159]
what to do if my x/y is more that 10, for example   var path = finder.findPath(0, 2, 0, 10, grid); i cant seem to show the if my values exceed to 9, what to do help ...

**Comment by brean** [comment]
I am not sure I understand your problem. Your grid can be way bigger than 10*10 nodes.

If you like to visualize your grid with the first row and column as numbered label you can for example create a html-table where you style your rows with a fixed width and height that can be big enough for any type of number. If you just output it using console.log then sure, you just have one character for your label but you could for example use alphabetical numbers like any spreadsheet software is doing so you would have the numbers from 0-9 and the letters from a-z, at least a 36*36 grid, even bigger when you also use special and uppercase characters or you could just print a number every 10th entry.

**Comment by lenskyAI123** [comment]
I'm confuse, help me out, if the first node is (0, 0) and use it as start node and (0, y) end/destination node, let y = last node in first column, what should be the value of y in finder.findPath(0, 0, 0, y, grid),? when i use number > 9 the path wont show up, every node is walkable btw,

**Comment by brean** [comment]
I guess the matrix for your grid is just 10 * 10 nodes big, the algorithm does not find that node and returns an empty list as path. Try a bigger map.
For example:
```
let matrix = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]];
let grid = new PF.Grid(11, 1, matrix);
let finder = new PF.AStarFinder();
let path = finder.findPath(0, 0, 10, 0, grid);
console.log(path[10]);
```

**Comment by lenskyAI123** [comment]
fixed.... thnx
