### ISSUE TITLE
Error following the example in Readme

### ISSUE THREAD

**Issue by el07694** [qiao/PathFinding.js#161]
Hello, 

Nice code!!

I have a little issue.
Following your example i have:

1) Put `<script src="pathfinding/visual/lib/pathfinding-browser.min.js"></script>` as first javascript importing
2) Put 	

```
var matrix = [
		[0, 0, 0, 1, 0],
		[1, 0, 0, 0, 1],
		[0, 0, 1, 0, 0],
	];
	var grid_from_lib = new PF.Grid(matrix);
	var finder = new PF.AStarFinder();
	var path = finder.findPath(1, 2, 4, 2, grid_from_lib);
	console.log(path);
```

into pacman.js file

Then the error in console is:

pathfinding-browser.min.js:1 Uncaught TypeError: Cannot read property '1' of undefined
    at r.getNodeAt (pathfinding-browser.min.js:1)
    at r.findPath (pathfinding-browser.min.js:1)
    at find_way (pacman.js:147)
    at initialize (pacman.js:100)
    at pacman.js:77

Any advice?
Thanks in advance!

*Edit: Same error when copying the above code in the end of: pathfinding/visual/index.html file

**Comment by el07694** [comment]
Is jquery required?

**Comment by brean** [comment]
1. jquery is not requrired.
2. please do not use the minified version for debugging.
3. I guess you are using the pathfinding-file from the demo? In that case you have to set width and height (It is outdated, consider building the code yourself). Anyway, this should work:
```
var matrix = [
		[0, 0, 0, 1, 0],
		[1, 0, 0, 0, 1],
		[0, 0, 1, 0, 0],
	];
	var grid_from_lib = new PF.Grid(5,3,matrix);
	var finder = new PF.AStarFinder();
	var path = finder.findPath(1, 2, 4, 2, grid_from_lib);
	console.log(path);
```

**Comment by el07694** [comment]
I tried this:

```
	var i,j;
	
	var grid_from_lib = new PF.Grid(26,26);
	for(i=0;i<26;i++){
		for(j=0;j<26;j++){
			if(squares[i][j]=="wall"){
				grid_from_lib.setWalkableAt(i, j, false);
			}else{
				grid_from_lib.setWalkableAt(i, j, true);
			}
		}
	}

	path = finder.findPath(x_start, y_start, x_end, y_end, grid_from_lib);

```
And works!
