### ISSUE TITLE
Find best route in array points

### ISSUE THREAD

**Issue by jfajardo** [qiao/PathFinding.js#169]
Hi, I have this array with points [(x1,y1),(x2,y2),.....(xn,yn)], how find best route with a start and end point?
Array of points:
```
0: (2) [130.88, 354.89]
1: (2) [122.18, 322.98]
2: (2) [153.31, 351.22]
3: (2) [172.04, 334.03]
4: (2) [207.09, 299.83]
5: (2) [231.48, 276.16]
6: (2) [245.4, 262.95]
7: (2) [257.48, 275.43]
8: (2) [272.44, 290.94]
9: (2) [292.67, 310.78]
10: (2) [318.43, 337.46]
11: (2) [337.61, 325.84]
12: (2) [338.26, 351.88]
13: (2) [355.18, 340.54]
14: (2) [375.93, 320.04]
15: (2) [358.31, 306.1]
16: (2) [395.11, 300.93]
17: (2) [434.08, 293.71]
18: (2) [473.06, 291.14]
19: (2) [505.49, 292.2]
20: (2) [531.19, 314.53]
21: (2) [401.48, 304.73]
22: (2) [375.27, 280.55]
23: (2) [344.31, 252.47]
24: (2) [324.58, 230.19]
25: (2) [297.55, 242.45]
26: (2) [278.77, 263.83]
```

The red dots are the points
![image](https://user-images.githubusercontent.com/4583818/54581907-a4eae100-49dc-11e9-8bc6-e685113128db.png)

**Comment by brean** [comment]
I think a navigation mesh based approach is best for you, take a look at this repository:
https://github.com/nickjanssen/PatrolJS

and this nice demo:
http://nickjanssen.github.io/PatrolJS/demo/demo.html

Pathfinding.js works on grid-maps to get the neighboring waypoints so you need to overwrite the functions that get the neighbors of the map as well as the calculation for the distance to use for example an A*-algorithm. 

Alternatively you could create a grid and change your map.
