### ISSUE TITLE
A* path finding showing incorrect path

### ISSUE THREAD

**Issue by nikhil-mahirrao** [qiao/PathFinding.js#174]
A* path finding showing incorrect path. Its going through the walls.

This is the input matrix
`const matrix = [
    [0, 0, 0, 0, 0],
    [0, 1, 0, 1, 1],
    [0, 0, 1, 0, 0],
    [1, 0, 0, 0, 1],
    [0, 0, 1, 0, 0]
  ];`

These are start and end points
`const startPoint = [0, 0];`
 `const endPoint = [4, 2];`
 `const path = finder.findPath(...startPoint, ...endPoint, grid);`

Output
`path:  [[0,0],[0,1],[0,2],[1,2],[1,3],[2,3],[3,3],[3,2],[4,2]]`

**Comment by brean** [comment]
I don't see it walking through walls, so let's draw that down:

| | 0 | 1 | 2 | 3 | 4 |
|-|-|-|-|-|-|
|__0__|0| | | | |
|__1__|1|X| |X|X|
|__2__|2|3|X|7|8|
|__3__|X|4|5|6|X|
|__4__| | |X| | |

Where X is an obstacle and the Numbers are the indices of the coordinates from your output path. Looks pretty perfect to me.
Maybe you confused x and y coordinates?
