### ISSUE TITLE
Matrix size

### ISSUE THREAD

**Issue by flightltd** [qiao/PathFinding.js#177]
Hi,

Can this be efficiently used to process paths on very large matrices with many thousands of columns and rows?

Cheers

**Comment by brean** [comment]
It depends on your hardware and how often you like to calculate the path. 
Especially if you have multiple agents you might want to take a look at [easystar](https://github.com/prettymuchbryce/easystarjs).

For your pathfinding in general you could also change the [getNeighbor](https://github.com/qiao/PathFinding.js/blob/master/src/core/Grid.js#L144) function of your grid to only get regions first and then have (hopefully optimal) fixed paths stored for those regions. Although this might lead to less accurate paths and costs more memory.

**Comment by flightltd** [comment]
Thank you for your help.

**Comment by flightltd** [comment]
It turned out that I didn't need more than a few hundred on each dimension and it works beautifully.
