### ISSUE TITLE
Getting every possible shortest path between two nodes

### ISSUE THREAD

**Issue by anand-010** [qiao/PathFinding.js#187]
Getting every possible shortest path between two nodes using dijkstra algorithm ( ranked by best path ). Any one getting javascript code that would be awesome.

**Comment by brean** [comment]
You can not have more than one shortest path. There can be multiple paths with the lowest cost, but there can only be one lowest cost, so PathFinding.js does exactly that for you. If you want all possible paths and their costs the list will be very long, just changing one node to a neighbouring one already is another path, so having this list is probably not very helpful.
