### ISSUE TITLE
Solve maze produced by https://github.com/bestguy/generate-maze

### ISSUE THREAD

**Issue by netgfx** [qiao/PathFinding.js#203]
The special thing here is that there are no blocks that are "walls" but rather if a block can be traversed by another from a specific position (left, right, top, bottom).
the maze here is constructed by blocks that look like this:
```
{
  bottom: true
  left: true
  right: false
  set: 1
  top: true
  x: 0
  y: 0
}
```

**Comment by brean** [comment]
That should not be a problem, in its core all path finding algorithms here use the same approach of looking at neighboring cells (eigher top right left bottom as well or even diagonal - see https://github.com/qiao/PathFinding.js/blob/master/src/core/Grid.js#L144 ). So we might just need a slightly different Grid-implementation that overwrites the getNeighbors function.

**Comment by netgfx** [comment]
Yes I've looked at that issue after I had posted mine. I think I've managed to solve this, by having the initial array which has this structure:
```
{x:0, y:0, left: true, top: false, bottom: true, right: false}
```
and I extended the getNeighbors to lookup whether or not a neighbor is accessible from the current x, y. 

it looks like this:
```
export function getWalkableAt(x, y, direction, maze) {
    var realX = x
    var realY = y
    var result = undefined
    for (var i = 0; i < maze.length; i++) {
        result = _.find(maze[i], function (o) {
            return o.x === realX && o.y === realY
        })
        if (result != undefined) {
            break
        }
    }
    
    if (result) {
        return !result[direction]
    } else {
        return false
    }
}
```

and the new getNeighbors:
```
// ↑
    if (getWalkableAt(x, y, "top", this.maze) && this.isWalkableAt(x, y - 1)) {
        neighbors.push(nodes[y - 1][x])
        s0 = true
    }
    // →
    if (
        getWalkableAt(x, y, "right", this.maze) &&
        this.isWalkableAt(x + 1, y)
    ) {
        neighbors.push(nodes[y][x + 1])
        s1 = true
    }
    // ↓
    if (
        getWalkableAt(x, y, "bottom", this.maze) &&
        this.isWalkableAt(x, y + 1)
    ) {
        neighbors.push(nodes[y + 1][x])
        s2 = true
    }
    // ←
    if (getWalkableAt(x, y, "left", this.maze) && this.isWalkableAt(x - 1, y)) {
        neighbors.push(nodes[y][x - 1])
        s3 = true
    }
 ```
Seems to be working fine. 

The only thing that I wish, it would be to be able to easily extend the `getNeighbors` function so I wouldn't have to copy over the Grid ,Node and the algorithm (BFS, etc) classes
