### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '6')

### ISSUE THREAD

**Issue by dommmmy** [qiao/PathFinding.js#215]
I got error message very confused:
TypeError: Cannot read properties of undefined (reading '6')
    at n.getNodeAt (pathfinding-browser.min.js:1:4462)
    at n.findPath (pathfinding-browser.min.js:1:9353)
    at new Enemy (sketch.js:22:22)
    
    My code is:
    
    var gameMap = [
  [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0],
  [0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0],
  [0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0],
];
var grid = new PF.Grid(gameMap);

var finder = new PF.AStarFinder({
  allowDiagonal: true,
});

var enemies = [];

playerX = 420;
playerY = 420;

function Enemy() {
  this.X = 210;
  this.Y = 210;
  this.path = finder.findPath(
    this.X / 70,
    this.Y / 70,
    playerX / 70,
    playerY / 70,
    grid
  );
  grid = new PF.Grid(gameMap);
}

function setup() {
  createCanvas(980, 600);

  enemies.push(new Enemy());
}

**Comment by brean** [comment]
1. 420 / 70 is 6, but your maps height is only 5.
1. If you downloaded pathfinding-browser.min.js from the https://qiao.github.io/PathFinding.js/visual/ side you need to set width and height of your grid, it does not get the array dimensions automatically from your gameMap. Rebuild pathfinding-browser.min.js using `gulp compile` or provide width and height.
