### ISSUE TITLE
Remove Trace algorithm as it is the same as BestFirstFinder

### ISSUE THREAD

**Issue by imor** [qiao/PathFinding.js#74]
BestFirstFinder calculates f as follows -

f = g + (h \* 1000000)

As the weight of the heuristic function h is huge, the heuristic function dictates which nodes should be expanded first hence the greedy behaviour.

TraceFinder calculates f as follows -

f = (g \* aNumberSmallerThanOne) + h

This again means that the effect of h is more pronounced than that of g.

This is also evident from test runs on actual maps where the order of node expansion is identical between the two algos. Try it yourself @ http://qiao.github.io/PathFinding.js/visual/

Ping @qiao @rafaelcastrocouto

**Comment by ArcaneEngineer** [comment]
P.S. TraceFinder expands less than BestFirstFinder, and runs faster, on my system. If anything, replace BestFirst with Trace?

**Comment by rafaelcastrocouto** [comment]
I think we should remove the trace TraceFinder for now since I still could not find an elegant solution to this kind of search. 
We should keep the BestFirstFinder and maybe add a parameter(slider in the demo) to control the '1000000' value.

**Comment by ArcaneEngineer** [comment]
Sorry Rafael, did not mean to interfere - it was just my observation. I sent you an email to ask further Q's.
