### ISSUE TITLE
Allow me to publish to npm registry

### ISSUE THREAD

**Issue by imor** [qiao/PathFinding.js#77]
Hi @qiao

Could you please add me as a collaborator for pathfinding on npm. See https://www.npmjs.org/doc/cli/npm-owner.html for details on how to do it.

imor

**Comment by imor** [comment]
My npmjs username is imor

**Comment by qiao** [comment]
Done.

Sorry for the delay; been quiet busy at work recently.

Thank you for all the contributions :+1:

**Comment by imor** [comment]
Cool thanks a lot.
