### ISSUE TITLE
Errors with path array

### ISSUE THREAD

**Issue by cscott5288** [qiao/PathFinding.js#85]
Great plugin!

I'm having a really unusual problem. Sometime, at random, I will get the following error from line 851 of pathfinding-browser.js:
Uncaught TypeError: Cannot read property '0' of undefined

It obviously has to do with smoothing. But when I deactivate smoothing I still get a random error in another line related to the path[0][0] not being set. It really is bizarre. There's nothing unusual as to how I am creating the path. Example of my parameters when the error happens:

var path = finder.findPath(113, 135, 140, 165, grid);

The grid, which is 800 x 300, is being re-created just before the path is created. I'm looping through a bunch of objects and setting nodes unwalkable just after creating the grid. I'm literally scrapping the old grid and creating a new one just before I create the path each time (not using the clone method).

The error is also happening at line 507:

Grid.prototype.setWalkableAt = function(x, y, walkable) {
    this.nodes[y][x].walkable = walkable;
};

Any idea why path[0][0] is somehow becoming undefined?

**Comment by imor** [comment]
Hi @cscott5288

When PathFinding.js is not able to find a path it returns an empty array. Can you check if the path being returned is an empty array? If the issue persists please post your full code.

Thanks,
imor

**Comment by cscott5288** [comment]
That's definitely what's happening, but I can't figure out why. The paramaters are all set correctly when it happens and the grid is just fine (or at least I think so). 

 var path = finder.findPath(spriteInMatrixX, spriteInMatrixY, spriteGoingInMatrixX, spriteGoingInMatrixY, grid);
                              
if (path[0] == undefined) {
                                       console.log(spriteInMatrixX); // 144
                                    console.log(spriteInMatrixY); // 157
                                    console.log(spriteGoingInMatrixX); // 107
                                    console.log(spriteGoingInMatrixY); // 166
                                    console.debug(grid); 
 }


Grid is showing up fine in the console. Unfortunately I can't copy + past it because it's enormous (800 x 300, so, lots of nodes. I think if the start x/y and going x/y are good, it must inevitably be something wrong with the grid, correct? But I don't know what to look for in the grid. Any pointers?

This is a separate issue, but since there are so many nodes in the grid, wouldn't it make sense for me to update the existing grid rather than creating a whole new one each time I update the grid? My game is going to update the grid very often. Like once every 3 seconds or so.

**Comment by cscott5288** [comment]
I've realized now that the errors have something to do with the size of the grid. I'm only getting errors when I try to set nodes walkable that are at the very end or beginning of the x/y axis (the following examples is with a 200 x 400 size grid):

BAD
(199,260)(200,260)(199,261)(200,261)
(199,100)(200,100)(199,101)(200,101)
(200,60)(201,60)(200,61)(201,61)

GOOD
(183,73)(184,73)(183,74)(184,74)
(58,150)(59,150)(58,151)(59,151)
(34,124)(35,124)(34,125)(35,125)


Why is 199(x) bad on a 200(x) x 400(y) grid? I understand that you're doing a switcheroo when creating the grid object: the y is the key number of the array (instead of x). Maybe that has something to do with it? Also, low values on x/y, such as anything below 10 throw errors (on a grid size of 200 x 400)...

**Comment by imor** [comment]
The grid clone method being slow is a known problem. See #33 for that. Hopefully I'll get around to fixing that sometime soon. Regarding the issue of the path being an empty array please check if there is really a path possible on your grid.

Regarding the good and bad coordinates, x coordinates larger than 199 on a 200x400 grid are definitely out of range because the counting is zero based. From your example, the following coordinates are out of range (200,260)(200,261)(200,100)(200,101)(200,60)(201,60)(200,61)(201,61). But I still can't explain why others are bad. For that I want to see your full code or at least an example which reproduces the issue. I'm looking for something on the lines of the following code snippet:

```javascript
var PF = require('./pathfinding-browser.js'),
    maxRows = 400,
    maxCols = 200,
    matrix = [],
    row, col, rowArray, grid, finder, path;

for (row = 0;row < maxRows;row++) {
    rowArray = [];
    for (col = 0;col < maxCols;col++) {
        rowArray.push(0);
    }
    matrix.push(rowArray);
}

grid = new PF.Grid(maxCols, maxRows, matrix);
finder = new PF.AStarFinder();
path = finder.findPath(199, 260, 0, 260, grid);
console.log(path);
```

Can you do that?

**Comment by imor** [comment]
Also it would really help if you can demonstrate the problem on a really tiny grid like 3x5 or something instead of 200x400.

**Comment by cscott5288** [comment]
Imor, all of the problems were from not accounting for the fact that the grid was zero-based. I had a function that was putting  sprites in the game in random x/y coordinates and when the game started, those x/y coordinates were set walkable/not-walkable in the graph. I had another function that was looping through each sprite and setting nodes in the graph walkable/not-walkable. Both functions were throwing errors because, in a 200 x 200 game, the 200 x 200 coordinate didn't exist, neither did the 200 x 15 coordinate and so on. 

There's nothing wrong with the graph being zero-based( in face, it should be), but I think it's counter-intuitive that the graph doesn't have a node for the largest extreme of both the x and y axis. Why not make graph.node an array that is 201 in length (with the max x being 200) instead of 200 (where the max is 199)? Otherwise, how else would you set that coordinate which exists in your game (if not on the grid) as walkable/non-walkable?

**Comment by cscott5288** [comment]
P.S. When I wrote "Why is 199(x) bad on a 200(x) x 400(y) grid?" I neglected to tell you that the console was outputting 4 coordinates at a time when the error was thrown. However, if only one of the coordinates of the 4 was bad, the console would log all 4 (because I was setting all 4 non-walkable at the same time, just the way I had it coded). So, yeah, that's why you have no explanation for why the others are bad (they actually weren't bad)

**Comment by imor** [comment]
Well I'm glad you found out the problems. I don't think it is counter-intuitive that on a zero based axis which has a total of X items the last item has to be addressed as X - 1.

Having said that I was thinking if this was not clear from the docs that the counting would be zero based and I could improve the situation for other users. So can you reflect back on what caused this confusion? I'd really appreciate your feedback.

And thanks for using PathFinding.js :+1:

**Comment by cscott5288** [comment]
it's more than changing the way the coordinate is addressed. You literally can't store data for the coordinate. let me put it this way, if you have a 3 x 3 grid, you cannot store walkable/notwalkable data for 6 of the 9 squares (66% of squares make up the extremes of the x and y axis), unless you were to subtract 1 from each node and not have 0 x/y values. But that wouldn't make sense to store 1,1 into 0,0 and 2,2 into 1, 1, etc. It doesn't so much affect me because I'm using a huge grid size. but it did cause a day of troubleshooting and, each time I check for a path or set nodes walkable/non in the grid, I have to pass all of my coordinates into a function to make sure they don't fall into non-existent grid space.

I would at least put something in the readme that mentions the grid cannot accommodate the furthest extreme of the x and y axis.

**Comment by imor** [comment]
>if you have a 3 x 3 grid, you cannot store walkable/nonwalkable data for 6 of the 9 squares

Completely false. Lets say we have the following empty grid:

_|Column1|Column2|Column3
-----|------------|-----------|------------
Row1|0|0|0
Row2|0|0|0
Row3|0|0|0

To set all the extreme right and extreme bottom cells to 1 do:
```javascript
grid.setWalkableAt(2, 0, false);
grid.setWalkableAt(2, 1, false);
grid.setWalkableAt(2, 2, false);
grid.setWalkableAt(0, 2, false);
grid.setWalkableAt(1, 2, false);
```

Following are the addresses of all the cells:

_|Column1|Column2|Column3
-----|------------|-----------|------------
Row1|(0,0)|(1,0)|(2,0)
Row2|(0,1)|(1,1)|(2,1)
Row3|(0,2)|(1,2)|(2,2)

>unless you were to subtract 1 from each node

Well if you have a 1 based system in your game you'll have to convert it into a zero based system to use PathFinding.js there is no other way.

>I would at least put something in the readme that mentions the grid cannot accommodate the furthest extreme of the x and y axis.

I'm sorry I can't put false information in the readme.

**Comment by cscott5288** [comment]
well, it's your script, I'm not going to tell you how to write it (lol). in the above example, i would think that your matrix size is 2 x 2. if it were 3 x 3, you would be able to represent both 0,0 and 0, 3 (the furthest extremes). i.e. the following coordinates on the y axis:
(0,0)
(0,1)
(0,2)
(0,3)

but in your example, you can't represent 3. you could only represent 3 if you made it 4 x 4. What you're doing is subtracting 1 from every coordinate on both the x and y axis so that it can fit into a zero-based array. but the zero-based array should accomodate the dimensions of the matrix, not the other way around. i.e. it should be bigger. 

matrixes are used to represent physical space. when someone says I have a room for rent that is 10 feet by 10 feet, they're not counting 0 as 1 (which would make it 9 x 9 feet). They're counting 0 as 0 and 1 as 1. 

furthermore, isn't it a heck of a lot easier and more intuitive to reference 0,2 (the matrix coordinate) as 0,2 (the array element) instead of 0,2 as 1,3? 

Just my two cents!

**Comment by imor** [comment]
I think you don't fully understand how Arrays work, please go read about them and maybe you'll see my point otherwise we'll just keep going in circles.

imor

**Comment by cscott5288** [comment]
i understand how arrays work... agree to disagree :p
