### ISSUE TITLE
Questions about recreating the grid matrix

### ISSUE THREAD

**Issue by cscott5288** [qiao/PathFinding.js#86]
I understand that the grid matrix needs to be recreated each time a path is found, but can you help me understand why? I assume the path finder needs to set values in the grid array to work. What values does it set? and is there ever a case where it is more efficient to programatically reset these values each time you re-use the grid, as opposed to recreating the grid?

**Comment by imor** [comment]
>I assume the path finder needs to set values in the grid array to work

Your assumption is correct. PathFinding.js sets the _opened_, _closed_ and _tested_ properties on a node instance. This may not be an exhaustive list and you can check the code to find possible other properties. 

> is there ever a case where it is more efficient to programatically reset these values each time you re-use the grid, as opposed to recreating the grid?

Don't know as I haven't tried it. Go ahead and create a test on jsperf.com and maybe it'll be useful for everyone else.
