### ISSUE TITLE
find path returning an empty array

### ISSUE THREAD

**Issue by majimboo** [qiao/PathFinding.js#90]
I am using the Astar path finder and on the first find path it gives the correct path but on the subsequent calls it gives an empty array.

Why is that? Should I instantiate Astar finder for each path to find? because I'm only instantiating the finder once now.

**Comment by majimboo** [comment]
I guess you have to `copy` this grid every time you find a path?

**Comment by imor** [comment]
A grid becomes dirty once a pathfinder uses it. You need to create a new one each time or clone it before using it for finding the path. See the `grid.clone()` method.

**Comment by DefecateRainbows** [comment]
Could you put this somewhere in the documentation? Preferably somewhere easy to find?

My apologies if it is already, I couldn't find it when I hopped around in there.
