### ISSUE TITLE
PF.DiagonalMovement.Never  not working

### ISSUE THREAD

**Issue by PrimeLens** [qiao/PathFinding.js#92]
Hi,  just want to say I love the work done here, especially the options and advanced options. I have this running in node using pathfinding 0.4.16. The PF.DiagonalMovement.Never  is giving patchy results.
Have tried both
var finder = new PF.AStarFinder({
    diagonalMovement: PF.DiagonalMovement.Never
});
and
var finder = new PF.BiAStarFinder({
    allowDiagonal: false
});

When walking from { x: 6, y: 3 } to  { x: 3, y: 0 } I'm getting the following path
[ [ 6, 3 ], [ 5, 3 ], [ 4, 4 ], [ 3, 4 ], [ 3, 3 ], [ 3, 2 ], [ 3, 1 ], [ 3, 0 ] ]
and you can see there is a diagonal in there [ 5, 3 ] to  [ 4, 4 ]

The following matrix was used for the above results
[ [ 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1 ],
  [ 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1 ],
  [ 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0 ],
  [ 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1 ],
  [ 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0 ],
  [ 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0 ],
  [ 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0 ],
  [ 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0 ],
  [ 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0 ],
  [ 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0 ],
  [ 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0 ],
  [ 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0 ],
  [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0 ],
  [ 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],
  [ 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1 ] ]

**Comment by imor** [comment]
Hi @PrimeLens, thanks for your interest in PathFinding.js. I tried your example with the latest in master and it gives me correct results. Can you please check?

My code is
```javascript
var matrix = [ 
[ 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1 ],
[ 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1 ],
[ 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0 ],
[ 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1 ],
[ 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0 ],
[ 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0 ],
[ 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0 ],
[ 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0 ],
[ 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0 ],
[ 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0 ],
[ 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0 ],
[ 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0 ],
[ 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0 ],
[ 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],
[ 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1 ] ];
var grid = new PF.Grid(15, 15, matrix);
var finder = new PF.AStarFinder({
    diagonalMovement: PF.DiagonalMovement.Never
});
var path = finder.findPath(6, 3, 3, 0, grid);
console.log(path);
```

The output is
```bash
[ [ 6, 3 ],
  [ 5, 3 ],
  [ 5, 4 ],
  [ 4, 4 ],
  [ 3, 4 ],
  [ 3, 3 ],
  [ 3, 2 ],
  [ 3, 1 ],
  [ 3, 0 ] ]
```

Please do not use the allowDiagonal option, it is deprecated. Use diagonalMovement.

Thanks

**Comment by PrimeLens** [comment]
I found the cause.
var newPath = PF.Util.smoothenPath(grid, path);
was adding the diagonals back in

**Comment by imor** [comment]
No prob :)
Closing.
